### ISSUE TITLE
OSError: utils/z_bins.txt not found

### ISSUE THREAD

**Issue by malmarri** [standard-aaron/clues#3]
Thanks for developing a great tool!

After downloading all the necessary libraries and running the following command:

`python3 clues/inference.py --times test.LCT --out test`

I recieve the following error:

```
Loading data and initializing model...
[2354.6730957  1538.61975098 2217.19482422 1956.91015625 2494.17871094
 1539.2088623  2992.20410156 1584.62756348 2346.37207031 2221.52661133
 2003.00219727 1459.40466309 2335.84326172 3105.34692383 1474.91210938
 1584.91821289 3483.16723633 3081.40795898 2713.59399414 1404.23950195
 2086.89233398 1984.15319824 3183.29858398 1758.13208008 1797.84375
 2176.24243164 2067.46069336 2565.19091797 1274.42443848 2618.69458008
 2690.66210938 1716.00610352 2226.81567383 2283.48730469 1424.26879883
 1572.77075195 2046.36303711 2602.83764648 3440.84082031 1653.07617188
 1922.74975586 1783.00048828 1374.31982422 1495.09338379 2233.21020508
 1674.3581543  1921.01171875 1890.9486084  1606.30358887 1823.51171875
 1595.35717773 1750.20288086 2365.08300781 2415.49414062 1230.37145996
 1933.81750488 2105.72314453 2165.26538086 2746.6484375  2368.70092773
 3397.77783203 1986.12084961 3155.92602539 2791.86157227 2417.0402832
 1521.60949707 2378.12451172 3423.56640625 1787.38623047 3201.46777344
 2183.44018555 1981.15942383 2204.89233398 2376.3605957  1813.30737305
 2082.43334961 1969.73254395 2519.78100586 2021.51184082 1706.61547852
 1924.04467773 2431.04101562 2222.87329102 2675.36767578 1355.68811035
 2062.38623047 1819.61706543 1958.13952637 1971.60913086 1644.28076172
 1635.79443359 2507.8425293  2078.40429688 2216.68994141 1833.70385742
 1411.10913086 2051.44238281 1864.87524414 3291.5534668  2342.11254883]
Traceback (most recent call last):
  File "clues/inference.py", line 276, in <module>
    timeBins,times,epochs,Ne,freqs,z_bins,z_logcdf,z_logsf,ancientGLs,noCoals,currFreq,h = load_data(args)
  File "clues/inference.py", line 169, in load_data
    z_bins,z_logcdf,z_logsf = load_normal_tables()
  File "clues/inference.py", line 87, in load_normal_tables
    z_bins = np.genfromtxt('utils/z_bins.txt')
  File "/lustre/scratch114/projects/my-venv/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1772, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/lustre/scratch114/projects/my-venv/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/lustre/scratch114/projects/my-venv/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: utils/z_bins.txt not found.
```
despite the z_bins.txt being in the utils folder. Do you have any idea how to solve this?

Thanks in advance.

**Comment by malmarri** [comment]
Moved the content of the utils folder to the directory that contains inference.py and it works fine. Closing.
